# Generated by Django 3.0.4 on 2020-03-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200327_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caregories',
            new_name='categories',
        ),
    ]
